# Generated by Django 2.2 on 2020-02-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
