# Generated by Django 2.2 on 2020-02-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0002_show_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
